#!/usr/bin/env bash
# Reach the other personal machine over Tailscale with plain OpenSSH.
# Generated by chezmoi from .chezmoitemplates/tailnet-ssh/tailnet.sh.
# Runs under macOS bash 3.2 too: no associative arrays, mapfile, or ${var@Q}.

set -euo pipefail

{{- if eq .chezmoi.os "darwin" }}
REMOTE_LABEL="Arch Linux desktop"
REMOTE_HOST="joeyarchlinux"
{{- else }}
REMOTE_LABEL="MacBook Air"
REMOTE_HOST="josephs-macbook-air"
{{- end }}
REMOTE_USER="josephwest"
KEY="$HOME/.ssh/tailnet_ed25519"
TARGET="$REMOTE_USER@$REMOTE_HOST"

SSH_OPTS=(
    -i "$KEY"
    -o IdentitiesOnly=yes
    -o BatchMode=yes
    -o ConnectTimeout=10
    -o ServerAliveInterval=15
    -o ServerAliveCountMax=4
)

usage() {
    cat <<EOF
Usage: $(basename "$0") <command> [args]

Remote: $REMOTE_LABEL ($TARGET), key $KEY

Commands:
  check              Diagnose connectivity and authentication.
  run [--] CMD...    Run CMD with bash on the remote, using its login-shell PATH.
                     Stdin is passed through; the remote exit code is returned.
  ssh [OPTS...] [-- CMD...]
                     ssh to the remote with extra ssh OPTS (e.g. -t for a TTY,
                     -N -L 3000:localhost:3000 for a tunnel). CMD, if given, is
                     wrapped like run.
  rsync [ARGS...]    rsync over the same ssh options. Write remote paths as
                     remote:PATH (relative to the remote home).
  target             Print user@host.
EOF
}

# Both machines log in to fish, so wrap CMD as base64 and decode it into bash
# under a login shell: that avoids fish/bash quoting differences and picks up
# Homebrew and other login-only PATH entries. Single-quoted text and "$(...)"
# parse the same way in fish (3.4+), zsh, and bash.
remote_bash() {
    local encoded
    encoded=$(printf '%s' "$1" | base64 | tr -d '\n')
    printf "exec \$SHELL -l -c 'exec bash -c \"\$(printf %%s %s | base64 --decode)\"'" "$encoded"
}

cmd_check() {
    echo "remote: $REMOTE_LABEL ($TARGET)"

    if [[ ! -r "$KEY" ]]; then
        echo "FAIL: missing key $KEY (see the skill's one-time setup)" >&2
        return 1
    fi

    if command -v tailscale >/dev/null 2>&1; then
        if tailscale ping -c 1 --timeout 5s "$REMOTE_HOST" >/dev/null 2>&1; then
            echo "ok: tailscale ping"
        else
            echo "warn: tailscale ping failed; the remote may be asleep, offline, or logged out of Tailscale" >&2
        fi
    fi

    local output status=0
    output=$(ssh "${SSH_OPTS[@]}" "$TARGET" "$(remote_bash 'echo "$(whoami)@$(uname -n) $(uname -s) $(uname -m)"')" 2>&1) || status=$?
    if [[ $status -eq 0 ]]; then
        echo "ok: ssh -> $output"
        return 0
    fi

    echo "FAIL: ssh exited $status: $output" >&2
    case "$output" in
        *"Permission denied"*) echo "hint: $KEY.pub is not in the remote ~/.ssh/authorized_keys" >&2 ;;
        *"Host key verification failed"*) echo "hint: no known_hosts entry for $REMOTE_HOST; verify the host key before adding it" >&2 ;;
        *"timed out"* | *"No route"* | *"Could not resolve"*) echo "hint: remote unreachable; check it is awake and on the tailnet" >&2 ;;
    esac
    return 1
}

main() {
    local command=${1:-}
    [[ $# -gt 0 ]] && shift

    case "$command" in
        check)
            cmd_check
            ;;
        run)
            [[ ${1:-} == "--" ]] && shift
            [[ $# -gt 0 ]] || { echo "run: missing command" >&2; exit 2; }
            exec ssh "${SSH_OPTS[@]}" "$TARGET" "$(remote_bash "$*")"
            ;;
        ssh)
            local opts=()
            while [[ $# -gt 0 && $1 != "--" ]]; do
                opts+=("$1")
                shift
            done
            [[ ${1:-} == "--" ]] && shift
            if [[ $# -gt 0 ]]; then
                exec ssh "${SSH_OPTS[@]}" ${opts[@]+"${opts[@]}"} "$TARGET" "$(remote_bash "$*")"
            fi
            exec ssh "${SSH_OPTS[@]}" ${opts[@]+"${opts[@]}"} "$TARGET"
            ;;
        rsync)
            local args=() arg
            for arg in "$@"; do
                if [[ $arg == remote:* ]]; then
                    arg="$TARGET:${arg#remote:}"
                fi
                args+=("$arg")
            done
            exec rsync -e "ssh ${SSH_OPTS[*]}" ${args[@]+"${args[@]}"}
            ;;
        target)
            echo "$TARGET"
            ;;
        -h | --help | help | "")
            usage
            ;;
        *)
            echo "unknown command: $command" >&2
            usage >&2
            exit 2
            ;;
    esac
}

main "$@"
