[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'secondary'
    3 = 'main'
    4 = 'secondary'
    5 = 'main'
    6 = 'secondary'
    7 = 'main'
    8 = 'secondary'
    9 = 'main'
    10 = 'secondary'

[mode.main.binding]
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-a = 'workspace a'
    alt-b = 'workspace b'
    alt-c = 'workspace c'
    alt-d = 'workspace d'
    alt-e = 'workspace e'
    alt-f = 'workspace f'
    alt-g = 'workspace g'
    alt-h = 'workspace h'
    alt-i = 'workspace i'
    alt-j = 'workspace j'
    alt-k = 'workspace k'
    alt-l = 'workspace l'
    alt-m = 'workspace m'
    alt-n = 'workspace n'
    alt-o = 'workspace o'
    alt-p = 'workspace p'
    alt-q = 'workspace q'
    alt-r = 'workspace r'
    alt-s = 'workspace s'
    alt-t = 'workspace t'
    alt-u = 'workspace u'
    alt-v = 'workspace v'
    alt-w = 'workspace w'
    alt-x = 'workspace x'
    alt-y = 'workspace y'
    alt-z = 'workspace z'

    alt-shift-a = 'workspace A'
    alt-shift-b = 'workspace B'
    alt-shift-c = 'workspace C'
    alt-shift-d = 'workspace D'
    alt-shift-e = 'workspace E'
    alt-shift-f = 'workspace F'
    alt-shift-g = 'workspace G'
    alt-shift-h = 'workspace H'
    alt-shift-i = 'workspace I'
    alt-shift-j = 'workspace J'
    alt-shift-k = 'workspace K'
    alt-shift-l = 'workspace L'
    alt-shift-m = 'workspace M'
    alt-shift-n = 'workspace N'
    alt-shift-o = 'workspace O'
    alt-shift-p = 'workspace P'
    alt-shift-q = 'workspace Q'
    alt-shift-r = 'workspace R'
    alt-shift-s = 'workspace S'
    alt-shift-t = 'workspace T'
    alt-shift-u = 'workspace U'
    alt-shift-v = 'workspace V'
    alt-shift-w = 'workspace W'
    alt-shift-x = 'workspace X'
    alt-shift-y = 'workspace Y'
    alt-shift-z = 'workspace Z'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-ctrl-a = 'move-node-to-workspace a'
    alt-ctrl-b = 'move-node-to-workspace b'
    alt-ctrl-c = 'move-node-to-workspace c'
    alt-ctrl-d = 'move-node-to-workspace d'
    alt-ctrl-e = 'move-node-to-workspace e'
    alt-ctrl-f = 'move-node-to-workspace f'
    alt-ctrl-g = 'move-node-to-workspace g'
    alt-ctrl-h = 'move-node-to-workspace h'
    alt-ctrl-i = 'move-node-to-workspace i'
    alt-ctrl-j = 'move-node-to-workspace j'
    alt-ctrl-k = 'move-node-to-workspace k'
    alt-ctrl-l = 'move-node-to-workspace l'
    alt-ctrl-m = 'move-node-to-workspace m'
    alt-ctrl-n = 'move-node-to-workspace n'
    alt-ctrl-o = 'move-node-to-workspace o'
    alt-ctrl-p = 'move-node-to-workspace p'
    alt-ctrl-q = 'move-node-to-workspace q'
    alt-ctrl-r = 'move-node-to-workspace r'
    alt-ctrl-s = 'move-node-to-workspace s'
    alt-ctrl-t = 'move-node-to-workspace t'
    alt-ctrl-u = 'move-node-to-workspace u'
    alt-ctrl-v = 'move-node-to-workspace v'
    alt-ctrl-w = 'move-node-to-workspace w'
    alt-ctrl-x = 'move-node-to-workspace x'
    alt-ctrl-y = 'move-node-to-workspace y'
    alt-ctrl-z = 'move-node-to-workspace z'

    alt-ctrl-shift-a = 'move-node-to-workspace A'
    alt-ctrl-shift-b = 'move-node-to-workspace B'
    alt-ctrl-shift-c = 'move-node-to-workspace C'
    alt-ctrl-shift-d = 'move-node-to-workspace D'
    alt-ctrl-shift-e = 'move-node-to-workspace E'
    alt-ctrl-shift-f = 'move-node-to-workspace F'
    alt-ctrl-shift-g = 'move-node-to-workspace G'
    alt-ctrl-shift-h = 'move-node-to-workspace H'
    alt-ctrl-shift-i = 'move-node-to-workspace I'
    alt-ctrl-shift-j = 'move-node-to-workspace J'
    alt-ctrl-shift-k = 'move-node-to-workspace K'
    alt-ctrl-shift-l = 'move-node-to-workspace L'
    alt-ctrl-shift-m = 'move-node-to-workspace M'
    alt-ctrl-shift-n = 'move-node-to-workspace N'
    alt-ctrl-shift-o = 'move-node-to-workspace O'
    alt-ctrl-shift-p = 'move-node-to-workspace P'
    alt-ctrl-shift-q = 'move-node-to-workspace Q'
    alt-ctrl-shift-r = 'move-node-to-workspace R'
    alt-ctrl-shift-s = 'move-node-to-workspace S'
    alt-ctrl-shift-t = 'move-node-to-workspace T'
    alt-ctrl-shift-u = 'move-node-to-workspace U'
    alt-ctrl-shift-v = 'move-node-to-workspace V'
    alt-ctrl-shift-w = 'move-node-to-workspace W'
    alt-ctrl-shift-x = 'move-node-to-workspace X'
    alt-ctrl-shift-y = 'move-node-to-workspace Y'
    alt-ctrl-shift-z = 'move-node-to-workspace Z'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
